name: node build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Build webui
      run: |
        set -x
        npm install
        npm run build

    - name: Prepare data
      run: |
        set -x
        mkdir -p data
        for f in $(find gzipped/static -name "*.js.gz" -o -name "*.css.gz"); do cp -f $f data; done
        cp -f gzipped/index.html.gz data/wifi.html.gz
        cp build/index.html data/wifi-cdn.html
        sed -i 's#href="#href="https://coderus.github.io/wifimanager-react-page#g' data/wifi-cdn.html
        sed -i 's#src="#src="https://coderus.github.io/wifimanager-react-page#g' data/wifi-cdn.html
        gzip data/wifi-cdn.html
      
    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: data

    - name: Create release
      if: github.ref == 'refs/heads/master'
      run: |
        set -x
        assets=()
        for asset in data/*.gz; do
          assets+=("-a" "$asset")
        done
        RELEASE_TAG="$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
        hub release create "${assets[@]}" -m "$RELEASE_TAG" "$RELEASE_TAG"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Deploy GH Actions
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        branch: gh-pages
